import React,{useEffect,useMemo,useState}from"react";
const N=["Andreas Moitzi","Annina Ebhardt","Anton Pleva","Bernd Engelbrecht","Christian Grasgruber","Christoph Krainer","David Edlinger","Georg Schenn","Gerwin Hofmeister","Jakob Beck","Marc Trummer","Martin Ehrenreich","Mathias Heschl","Nikolaus Kronabitter","Patrick Gruber","Patrick Tatzer","Simon Kampitsch","Stefan Gruber","Stefan Steiner"];
const TIMES=["00:00-00:30","00:30-01:00","01:00-01:30","01:30-02:00"],G="__guest__",HK="rscg-history-v5",SK="rscg-selection-v5";
const empty=()=>Array.from({length:8},()=>({type:"fixed",value:"",guest:""}));
const emptyFix=()=>Array.from({length:4},()=>Array.from({length:2},()=>({a:"",b:""})));
function shuffle(x){x=[...x];for(let i=x.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function pk(a,b){return[a.toLowerCase(),b.toLowerCase()].sort().join("|")}
function matchings(x){if(!x.length)return[[]];let f=x[0],r=[];for(let i=1;i<x.length;i++){let rest=x.filter((_,k)=>k!==0&&k!==i);for(let m of matchings(rest))r.push([[f,x[i]],...m])}return r}
const MS=matchings([0,1,2,3,4,5,6,7]);
function make(players,history,fix){let used=new Set(),chosen=[],past=new Map();history.forEach(h=>(h.pairs||[]).forEach(k=>past.set(k,(past.get(k)||0)+1)));
 function go(r){if(r===4)return true;let fixed=fix[r].filter(p=>p.a!==""&&p.b!=="").map(p=>[+p.a,+p.b]);let fixedKeys=new Set(fixed.map(([a,b])=>pk(players[a],players[b])));let cand=MS.filter(m=>fixed.every(([a,b])=>m.some(([x,y])=>(x===a&&y===b)||(x===b&&y===a)))).filter(m=>r===3||m.every(([a,b])=>fixedKeys.has(pk(players[a],players[b]))||!used.has(pk(players[a],players[b])))).map(m=>({m,score:m.reduce((s,[a,b])=>fixedKeys.has(pk(players[a],players[b]))?s:s+(past.get(pk(players[a],players[b]))||0)+(r===3&&used.has(pk(players[a],players[b]))?1:0),0)+Math.random()/10})).sort((a,b)=>a.score-b.score);
 for(let c of cand.slice(0,50)){let keys=c.m.map(([a,b])=>pk(players[a],players[b])).filter(k=>!fixedKeys.has(k));keys.forEach(k=>used.add(k));chosen.push(shuffle(c.m));if(go(r+1))return true;chosen.pop();keys.forEach(k=>used.delete(k))}return false}
 if(!go(0))return null;return chosen.map(t=>{t=shuffle(t);return[{court:1,a:t[0],b:t[1]},{court:2,a:t[2],b:t[3]}]})}
function Team({p,n,c}){return <div className={`team ${c}`}><div>{n[p[0]]}</div><small>&amp;</small><div>{n[p[1]]}</div></div>}
export default function App(){const[sel,setSel]=useState(empty),[players,setPlayers]=useState([]),[sched,setSched]=useState(null),[edit,setEdit]=useState(true),[fix,setFix]=useState(emptyFix),[showFix,setShowFix]=useState(false),[history,setHistory]=useState([]),[showHist,setShowHist]=useState(false),[msg,setMsg]=useState("");
 useEffect(()=>{try{let s=JSON.parse(localStorage.getItem(SK)||"null"),h=JSON.parse(localStorage.getItem(HK)||"[]");if(s?.length===8)setSel(s);if(Array.isArray(h))setHistory(h)}catch{}},[]);
 let names=useMemo(()=>sel.map(x=>(x.type==="guest"?x.guest:x.value).trim()),[sel]),selected=new Set(sel.filter(x=>x.type==="fixed"&&x.value).map(x=>x.value));
 let valid=names.every(Boolean)&&new Set(names.map(x=>x.toLowerCase())).size===8;
 let fixValid=fix.every(round=>{let u=[];for(let p of round){if((p.a==="")!==(p.b===""))return false;if(p.a!==""){if(p.a===p.b)return false;u.push(p.a,p.b)}}return new Set(u).size===u.length});
 function setChoice(i,v){setSel(s=>s.map((x,k)=>k!==i?x:v===G?{type:"guest",value:"",guest:""}:{type:"fixed",value:v,guest:""}));setSched(null)}
 function accept(){setPlayers(names);setEdit(false);setSched(null);localStorage.setItem(SK,JSON.stringify(sel))}
 function draw(){let s=make(players,history,fix);if(!s)setMsg("Mit diesen Fixierungen konnte kein gueltiger Spielplan erstellt werden.");else{setSched(s);setMsg("")}}
 function updateFix(r,i,f,v){setFix(x=>x.map((rr,ri)=>ri!==r?rr:rr.map((p,pi)=>pi!==i?p:{...p,[f]:v})));setSched(null)}
 function saveHist(){let pairs=sched.flatMap(r=>r.flatMap(m=>[pk(players[m.a[0]],players[m.a[1]]),pk(players[m.b[0]],players[m.b[1]])]));let next=[{id:Date.now(),date:new Date().toLocaleDateString("de-AT"),players,pairs},...history];setHistory(next);localStorage.setItem(HK,JSON.stringify(next));setMsg("Training in Partnerhistorie gespeichert.")}
 function whatsapp(){let l=["🎾 *RSCG Training*",""];sched.forEach((r,i)=>{l.push(`*Runde ${i+1} (${TIMES[i]})*`);r.forEach(m=>l.push(`Platz ${m.court}: ${players[m.a[0]]} / ${players[m.a[1]]} vs. ${players[m.b[0]]} / ${players[m.b[1]]}`));l.push("")});open(`https://wa.me/?text=${encodeURIComponent(l.join("\n"))}`,"_blank")}
 return <main><div className="wrap"><header><div className="tags"><b>2 Plaetze</b><span>19 Stammspieler + Gaeste</span><span>4 x 30 Minuten</span></div><h1>RSCG <em>Training</em></h1><p>Teilnehmer auswaehlen, feste Teams fuer einzelne oder alle vier Runden definieren und nur die restlichen Spieler automatisch auslosen. In Runde 4 duerfen sich automatisch ausgeloste Teams wiederholen.</p></header><div className="layout"><aside className="panel"><div className="title"><h2>Teilnehmer</h2>{!edit&&<button className="link" onClick={()=>setEdit(true)}>Aendern</button>}</div>{edit?<div className="list">{sel.map((x,i)=><div className="pick" key={i}><label><b>{i+1}</b> Teilnehmer {i+1}</label><select value={x.type==="guest"?G:x.value} onChange={e=>setChoice(i,e.target.value)}><option value="">Namen auswaehlen</option>{N.map(n=><option key={n} value={n} disabled={selected.has(n)&&x.value!==n}>{n}</option>)}<option value={G}>+ Gastspieler</option></select>{x.type==="guest"&&<input value={x.guest} placeholder="Name des Gastes" onChange={e=>setSel(s=>s.map((y,k)=>k===i?{...y,guest:e.target.value}:y))}/>}</div>)}{!valid&&<div className="warn">Bitte acht unterschiedliche Teilnehmer auswaehlen.</div>}<button className="primary" disabled={!valid} onClick={accept}>Teilnehmer uebernehmen</button></div>:<><div className="chips">{players.map((n,i)=><div key={n}><b>{i+1}.</b> {n}</div>)}</div><button className="secondary fixbutton" onClick={()=>setShowFix(!showFix)}>Fixe Paarungen {showFix?"ausblenden":"festlegen"}</button>{showFix&&<div className="fixes">{fix.map((round,r)=><div className="fixround" key={r}><strong>Runde {r+1}</strong>{round.map((p,i)=>{let used=new Set(round.flatMap((q,k)=>k===i?[]:[q.a,q.b]).filter(Boolean));return <div className="fixpair" key={i}><select value={p.a} onChange={e=>updateFix(r,i,"a",e.target.value)}><option value="">Kein fixes Team</option>{players.map((n,k)=><option key={n} value={k} disabled={used.has(String(k))||p.b===String(k)}>{n}</option>)}</select><span>+</span><select value={p.b} onChange={e=>updateFix(r,i,"b",e.target.value)}><option value="">Partner waehlen</option>{players.map((n,k)=><option key={n} value={k} disabled={used.has(String(k))||p.a===String(k)}>{n}</option>)}</select></div>})}</div>)}{!fixValid&&<div className="warn">Fixierungen muessen vollstaendig und ohne doppelte Spieler pro Runde sein.</div>}<button className="secondary" onClick={()=>setFix(emptyFix())}>Fixierungen loeschen</button></div>}</>}
 <div className="actions"><button className="primary big" disabled={edit||players.length!==8||!fixValid} onClick={draw}>{sched?"Neu auslosen":"Vier Runden auslosen"}</button>{sched&&<><button className="wa" onClick={whatsapp}>Per WhatsApp teilen</button><button className="secondary" onClick={()=>print()}>Drucken / PDF</button><button className="secondary" onClick={saveHist}>In Historie speichern</button></>}<button className="secondary" onClick={()=>setShowHist(!showHist)}>Partnerhistorie ({history.length})</button>{msg&&<div className="note">{msg}</div>}</div><div className="rule"><b>Regel:</b> Automatisch ausgeloste Teams werden in den Runden 1 bis 3 nicht wiederholt. In Runde 4 ist eine Wiederholung erlaubt. Fixierte Teams duerfen in mehreren oder allen vier Runden gleich bleiben.</div></aside><section className="content">{showHist&&<div className="panel hist"><div className="title"><h2>Partnerhistorie</h2><button className="link danger" onClick={()=>{setHistory([]);localStorage.removeItem(HK)}}>Loeschen</button></div>{history.length?history.map(h=><div className="hentry" key={h.id}><b>{h.date}</b><span>{h.players.join(", ")}</span></div>):<p>Noch keine Trainings gespeichert.</p>}</div>}{!sched?<div className="empty"><h2>Bereit zur Auslosung</h2><p>Waehle links acht Personen und optional fixe Paarungen aus.</p></div>:sched.map((r,i)=><article className="panel round" key={i}><div className="rhead"><h2>Runde {i+1}</h2><span>{TIMES[i]}</span></div><div className="courts">{r.map(m=><div className="court" key={m.court}><div className="ct"><b>Platz {m.court}</b><span>Match</span></div><div className="vs"><Team p={m.a} n={players} c="blue"/><b>VS</b><Team p={m.b} n={players} c="pink"/></div></div>)}</div></article>)}</section></div></div></main>}
